name: cw_food_ordering
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
#  firebase_auth: ^5.3.0
#  firebase_core: ^3.5.0
  firebase_core: ^3.3.0  # Downgrade to a stable version
  firebase_auth: ^5.1.0  # Downgrade to match firebase_core
  firebase_core_web: 2.17.4  # Use a stable version
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
  country_code_picker_plus: ^0.0.9
  logger: ^2.5.0
  flutter_launcher_icons: ^0.14.1
  package_info_plus: ^8.1.1
#  graphql_flutter: ^5.1.2   # For integrating GraphQL API and handling data asynchronously
  connectivity_plus: ^6.0.3  # Use a stable version
  provider: ^6.1.2
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_otp_text_field: ^1.2.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0


  hexcolor: ^3.0.1
  shimmer: ^3.0.0
  uuid: ^4.5.1
  razorpay_flutter: ^1.3.7
  flutter_svg: ^2.0.16
  flutter_local_notifications: ^18.0.1
  json_annotation: ^4.9.0
  confetti: ^0.8.0
  qr_flutter: ^4.1.0
  flutter_switch: ^0.3.2
#  connectivity_plus: ^6.1.3
  # Add these dependencies for voice search functionality
  speech_to_text: ^6.3.0
  permission_handler: ^10.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/svg/payment/payment_credit.svg
    - assets/images/svg/payment/payment_google.svg
    - assets/images/svg/payment/payment_paypal.svg
    - assets/images/svg/payment/razorpay.svg
    - assets/images/default_promotion.png
    - assets/images/categories.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cw_food_logo.png"

