// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ5q5h8QIfDuU55Ib8_9fy6XXc9EPePSk',
    appId: '1:910425365277:web:0be9de345c04802a6b9ff4',
    messagingSenderId: '910425365277',
    projectId: 'cw-food-ordering',
    authDomain: 'cw-food-ordering.firebaseapp.com',
    storageBucket: 'cw-food-ordering.appspot.com',
    measurementId: 'G-DXQ6JKXDD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvpsZ8Dsi7n67Gr77wdfS_s7XJD1ljGS0',
    appId: '1:910425365277:android:968761a03dbfb8f46b9ff4',
    messagingSenderId: '910425365277',
    projectId: 'cw-food-ordering',
    storageBucket: 'cw-food-ordering.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKwuoNyrcSGvVERaB1xy0n62EZnkQSDc',
    appId: '1:910425365277:ios:d8827f97aaf9945b6b9ff4',
    messagingSenderId: '910425365277',
    projectId: 'cw-food-ordering',
    storageBucket: 'cw-food-ordering.appspot.com',
    iosBundleId: 'com.reusable.firebasePhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfKwuoNyrcSGvVERaB1xy0n62EZnkQSDc',
    appId: '1:910425365277:ios:d8827f97aaf9945b6b9ff4',
    messagingSenderId: '910425365277',
    projectId: 'cw-food-ordering',
    storageBucket: 'cw-food-ordering.appspot.com',
    iosBundleId: 'com.reusable.firebasePhoneAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ5q5h8QIfDuU55Ib8_9fy6XXc9EPePSk',
    appId: '1:910425365277:web:27e71d6abaa27ca46b9ff4',
    messagingSenderId: '910425365277',
    projectId: 'cw-food-ordering',
    authDomain: 'cw-food-ordering.firebaseapp.com',
    storageBucket: 'cw-food-ordering.appspot.com',
    measurementId: 'G-KLQWQN2WGB',
  );
}
